service: agence_gare_monaco

image: laurentqro/agence-gare-monaco

servers:
  web:
    - 100.111.226.59

proxy:
  ssl: true
  hosts:
    - agencegaremonaco.com
    - www.agencegaremonaco.com

registry:
  server: ghcr.io
  username: laurentqro
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    SITE_HOST: https://agencegaremonaco.com

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "agence_gare_monaco_storage:/rails/storage"
  - "agence_gare_monaco_tours:/rails/public/tours"

asset_path: /rails/public/assets

builder:
  remote: ssh://ubuntu@100.111.226.59
  arch: amd64

ssh:
  user: ubuntu
