service: agence_gare_monaco

image: laurentqro/agence-gare-monaco

servers:
  web:
    - 46.225.227.128

proxy:
  ssl: true
  host: curau.dev

registry:
  server: ghcr.io
  username: laurentqro
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    SITE_HOST: https://curau.dev

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "agence_gare_monaco_storage:/rails/storage"
  - "agence_gare_monaco_tours:/rails/public/tours"

asset_path: /rails/public/assets

builder:
  remote: ssh://root@46.225.227.128
  arch: amd64
